import React, { ComponentPropsWithRef } from 'react'

const SelectCountry = React.forwardRef<HTMLSelectElement, ComponentPropsWithRef<'select'>>(
  ({ onChange, onBlur, ...props }, ref) => (
    <>
      <select name='Country' id='pardot_country' ref={ref} onChange={onChange} onBlur={onBlur}>
        <option defaultValue='Country'>Country</option>
        <option value='Afghanistan'>Afghanistan</option>
        <option value='Algeria'>Algeria</option>
        <option value='Angola'>Angola</option>
        <option value='Argentina'>Argentina</option>
        <option value='Armenia'>Armenia</option>
        <option value='Australia'>Australia</option>
        <option value='Austria'>Austria</option>
        <option value='Bahamas'>Bahamas</option>
        <option value='Bangladesh'>Bangladesh</option>
        <option value='Belgium'>Belgium</option>
        <option value='Belize'>Belize</option>
        <option value='Benin'>Benin</option>
        <option value='Bermuda'>Bermuda</option>
        <option value='Bolivia'>Bolivia</option>
        <option value='Brazil'>Brazil</option>
        <option value='Bulgaria'>Bulgaria</option>
        <option value='Cameroon'>Cameroon</option>
        <option value='Canada'>Canada</option>
        <option value='Chile'>Chile</option>
        <option value='China'>China</option>
        <option value='Colombia'>Colombia</option>
        <option value='Congo'>Congo</option>
        <option value='Costa Rica'>Costa Rica</option>
        <option value='Croatia'>Croatia</option>
        <option value='Cuba'>Cuba</option>
        <option value='Cyprus'>Cyprus</option>
        <option value='Czech Republic'>Czech Republic</option>
        <option value='Czechia'>Czechia</option>
        <option value='Denmark'>Denmark</option>
        <option value='Ecuador'>Ecuador</option>
        <option value='Egypt'>Egypt</option>
        <option value='El Salvador'>El Salvador</option>
        <option value='Estonia'>Estonia</option>
        <option value='Finland'>Finland</option>
        <option value='France'>France</option>
        <option value='Germany'>Germany</option>
        <option value='Ghana'>Ghana</option>
        <option value='Greece'>Greece</option>
        <option value='Guatemala'>Guatemala</option>
        <option value='Haiti'>Haiti</option>
        <option value='Hong Kong'>Hong Kong</option>
        <option value='Hungary'>Hungary</option>
        <option value='Iceland'>Iceland</option>
        <option value='India'>India</option>
        <option value='Indonesia'>Indonesia</option>
        <option value='Iran'>Iran</option>
        <option value='Ireland'>Ireland</option>
        <option value='Israel'>Israel</option>
        <option value='Italy'>Italy</option>
        <option value='Jamaica'>Jamaica</option>
        <option value='Japan'>Japan</option>
        <option value='Kazakhstan'>Kazakhstan</option>
        <option value='Kenya'>Kenya</option>
        <option value='Kuala Lumpur'>Kuala Lumpur</option>
        <option value='Kuwait'>Kuwait</option>
        <option value='Latvia'>Latvia</option>
        <option value='Lebanon'>Lebanon</option>
        <option value='Libya'>Libya</option>
        <option value='Liechtenstein'>Liechtenstein</option>
        <option value='Lithuania'>Lithuania</option>
        <option value='London'>London</option>
        <option value='Luxembourg'>Luxembourg</option>
        <option value='Macao'>Macao</option>
        <option value='Madagascar'>Madagascar</option>
        <option value='Malawi'>Malawi</option>
        <option value='Malaysia'>Malaysia</option>
        <option value='Mauritius'>Mauritius</option>
        <option value='Mexico'>Mexico</option>
        <option value='Mongolia'>Mongolia</option>
        <option value='Morocco'>Morocco</option>
        <option value='Netherlands'>Netherlands</option>
        <option value='New Zealand'>New Zealand</option>
        <option value='Nicaragua'>Nicaragua</option>
        <option value='Nigeria'>Nigeria</option>
        <option value='Norway'>Norway</option>
        <option value='Oman'>Oman</option>
        <option value='Pakistan'>Pakistan</option>
        <option value='Panama'>Panama</option>
        <option value='Papua New Guinea'>Papua New Guinea</option>
        <option value='Paraguay'>Paraguay</option>
        <option value='Peru'>Peru</option>
        <option value='Philippines'>Philippines</option>
        <option value='Poland'>Poland</option>
        <option value='Portugal'>Portugal</option>
        <option value='Qatar'>Qatar</option>
        <option value='Romania'>Romania</option>
        <option value='Russia'>Russia</option>
        <option value='Russian Federation'>Russian Federation</option>
        <option value='Saint Kitts and Nevis'>Saint Kitts and Nevis</option>
        <option value='Saudi Arabia'>Saudi Arabia</option>
        <option value='Senegal'>Senegal</option>
        <option value='Slovakia'>Slovakia</option>
        <option value='Slovenia'>Slovenia</option>
        <option value='South Africa'>South Africa</option>
        <option value='South Korea'>South Korea</option>
        <option value='Spain'>Spain</option>
        <option value='Sri Lanka'>Sri Lanka</option>
        <option value='Suriname'>Suriname</option>
        <option value='Sweden'>Sweden</option>
        <option value='Switzerland'>Switzerland</option>
        <option value='Syria'>Syria</option>
        <option value='Taiwan'>Taiwan</option>
        <option value='Tanzania'>Tanzania</option>
        <option value='Thailand'>Thailand</option>
        <option value='Trinidad and Tobago'>Trinidad and Tobago</option>
        <option value='Tunisia'>Tunisia</option>
        <option value='Turkey'>Turkey</option>
        <option value='Uganda'>Uganda</option>
        <option value='Ukraine'>Ukraine</option>
        <option value='United Arab Emirates'>United Arab Emirates</option>
        <option value='United Kingdom'>United Kingdom</option>
        <option value='United States of America'>United States of America</option>
        <option value='Uzbekistan'>Uzbekistan</option>
        <option value='Vietnam'>Vietnam</option>
        <option value='Zambia'>Zambia</option>
        <option value='Zimbabwe'>Zimbabwe</option>
      </select>
    </>
  )
)
export default SelectCountry
